# yaml-language-server: $schema=../crd/bases/jarvis.io_commands.yaml
apiVersion: jarvis.io/v1
kind: Command
metadata:
  name: kubelet-status
  namespace: jarvis
spec:
  command: ctr namespace ls
  selector:
    matchLabels:
      kubernetes.io/os: linux
    matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
          - kind-control-plane
          - kind-worker
