apiVersion: jarvis.io/v1
kind: Command
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: command-sample
  namespace: jarvis
spec:
  command: ps -eo pid,comm,%cpu,%mem --sort=-%cpu
